/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.AdsImpl;
import dao.AdsIntf;
import dao.UserImpl;
import dao.UserIntf;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

import model.Ads;
import model.User;
import util.ComboItem;


/**
 *
 * @author Viorel
 */
public class MainApp extends javax.swing.JFrame {   
    private Ads _ads;
    private User _user;
    private boolean beginPostAds;
    /**
     * Creates new form KijijiForm
     */
    public MainApp() {
        initComponents();
        setAdsNameList();
        setUsertoComponents(loadUserInfo(1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAds = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAdsTitle = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAdsMessage = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIntervalTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAdress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonBrowser = new javax.swing.JButton();
        jLabelImegaesPath = new javax.swing.JLabel();
        jTextFieldYoutubeUrl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldwww = new javax.swing.JTextField();
        jComboBoxAds = new javax.swing.JComboBox();
        jButtonNewAds = new javax.swing.JButton();
        jButtonDeleteAds = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAccountName = new javax.swing.JTextField();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordFieldConfirmationNewPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordFieldOldPassword = new javax.swing.JPasswordField();
        jTextFieldRedirectUrl = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonSaveUpdateUserPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Ads Title");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldAdsTitle))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldAdsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Ads Message");

        jTextAreaAdsMessage.setColumns(20);
        jTextAreaAdsMessage.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAdsMessage);

        jLabel3.setText("Interval time");

        jTextFieldIntervalTime.setText("0");

        jLabel4.setText("Min.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntervalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIntervalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");
        jButtonStop.setEnabled(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStart)
                .addGap(3, 3, 3)
                .addComponent(jButtonStop)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonStop))
                .addContainerGap())
        );

        jLabel5.setText("Adress");

        jTextFieldAdress.setText("adress");

        jLabel6.setText("Images path");

        jLabel7.setText("YouTube");

        jButtonBrowser.setText("browser");
        jButtonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowserActionPerformed(evt);
            }
        });

        jLabelImegaesPath.setText("path");

        jTextFieldYoutubeUrl.setText("url");

        jLabel9.setText("Phone");

        jTextFieldPhoneNumber.setText("Phone number");

        jLabel14.setText("www.");

        jTextFieldwww.setText("name.domen");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdress)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonBrowser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelImegaesPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldYoutubeUrl)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldwww)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonBrowser)
                    .addComponent(jLabelImegaesPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldYoutubeUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldwww, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jComboBoxAds.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAdsItemStateChanged(evt);
            }
        });

        jButtonNewAds.setText("New Ads");
        jButtonNewAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewAdsActionPerformed(evt);
            }
        });

        jButtonDeleteAds.setText("Delete Ads");
        jButtonDeleteAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAdsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBoxAds, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNewAds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeleteAds)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewAds)
                    .addComponent(jButtonDeleteAds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneAds.addTab("Advertisments", jPanel2);

        jLabel8.setText("Account name");

        jTextFieldAccountName.setText("nick or email");

        jPasswordFieldNewPassword.setText("jPasswordField1");

        jLabel10.setText("New Password");

        jPasswordFieldConfirmationNewPassword.setText("jPasswordField2");

        jLabel11.setText("Confirm new Password");

        jLabel12.setText("Old Password");

        jPasswordFieldOldPassword.setText("jPasswordField3");

        jLabel13.setText("RedirectUrl");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordFieldConfirmationNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(199, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRedirectUrl))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jPasswordFieldOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordFieldConfirmationNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRedirectUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jButtonSaveUpdateUserPassword.setText("Save");
        jButtonSaveUpdateUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveUpdateUserPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonSaveUpdateUserPassword)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSaveUpdateUserPassword)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPaneAds.addTab("User", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAds)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAds)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        disableEnableElements(true);
        if(thread!=null){
         thread.stop();   
        }  
        
       // postAds(false);
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        disableEnableElements(false);
         postAds();
         thread.start();
       
        
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
       saveUpdateAds(_ads);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSaveUpdateUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveUpdateUserPasswordActionPerformed
      saveUpdateUser();
        
    }//GEN-LAST:event_jButtonSaveUpdateUserPasswordActionPerformed

    private void jButtonBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowserActionPerformed
        JFrame frame = new JFrame();
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        chooser.setMultiSelectionEnabled(true);
        int returnVal = chooser.showOpenDialog(frame);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jLabelImegaesPath.setText(getImagesName(chooser.getSelectedFiles()));
        }
    }//GEN-LAST:event_jButtonBrowserActionPerformed

    private void jButtonNewAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewAdsActionPerformed
        newAds();
    }//GEN-LAST:event_jButtonNewAdsActionPerformed

    private void jButtonDeleteAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAdsActionPerformed
        deleteAds();
    }//GEN-LAST:event_jButtonDeleteAdsActionPerformed

    private void jComboBoxAdsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAdsItemStateChanged
       Object item = jComboBoxAds.getSelectedItem();
       if(item!=null){
    	   String valueAdsId = ((ComboItem)item).getValue();
           persistAds(valueAdsId);
           setAdstoComponents(_ads);  
       }
        
    }//GEN-LAST:event_jComboBoxAdsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
               /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowser;
    private javax.swing.JButton jButtonDeleteAds;
    private javax.swing.JButton jButtonNewAds;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveUpdateUserPassword;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JComboBox jComboBoxAds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImegaesPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordFieldConfirmationNewPassword;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JPasswordField jPasswordFieldOldPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneAds;
    private javax.swing.JTextArea jTextAreaAdsMessage;
    private javax.swing.JTextField jTextFieldAccountName;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldAdsTitle;
    private javax.swing.JTextField jTextFieldIntervalTime;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldRedirectUrl;
    private javax.swing.JTextField jTextFieldYoutubeUrl;
    private javax.swing.JTextField jTextFieldwww;
    // End of variables declaration//GEN-END:variables

    private void disableEnableElements(boolean enable) {       
        jComboBoxAds.setEnabled(enable);
        jTextFieldAdsTitle.setEnabled(enable);
        jTextAreaAdsMessage.setEnabled(enable);
        jTextFieldAdress.setEnabled(enable);
        jTextFieldYoutubeUrl.setEnabled(enable);
        jTextFieldPhoneNumber.setEnabled(enable);
        jTextFieldIntervalTime.setEnabled(enable);
        jButtonBrowser.setEnabled(enable);
        jButtonSave.setEnabled(enable);
        jButtonStart.setEnabled(enable);
        jButtonStop.setEnabled(!enable);
        jTextFieldwww.setEnabled(enable);
        jButtonDeleteAds.setEnabled(enable);
        jButtonNewAds.setEnabled(enable);
        jTextFieldAccountName.setEnabled(enable);
        jPasswordFieldOldPassword.setEnabled(enable);
        jPasswordFieldNewPassword.setEnabled(enable);
        jPasswordFieldConfirmationNewPassword.setEnabled(enable);
        jButtonSaveUpdateUserPassword.setEnabled(enable);
        jTextFieldRedirectUrl.setEnabled(enable);         
    }

    private void saveUpdateAds(Ads ads) {
        setAllFildsToAds();
     AdsIntf adsBc =  AdsImpl.getInstance();
        if (ads!=null && ads.getId()<=0) {
            adsBc.saveAds(_ads);
        } else {
            adsBc.updateAds(_ads);
        }
        setAdsNameList();
    }
    private void saveUpdateUser(){
     setAllFildsToUser();
     UserIntf userBc=UserImpl.getInstance();
     if(_user.getId()>0){
         userBc.updateUser(_user);
     }else{
         userBc.saveUser(_user);
     } 
    }
    
    private User loadUserInfo(Integer id){
        User user =new User();
        UserIntf userBc=UserImpl.getInstance();
        user=userBc.getUserById(id);
     return user;
    }

    private void setAdstoComponents(Ads ads) {      
        if (ads!=null) {
            jTextFieldAdsTitle.setText(ads.getTitle());
            jTextAreaAdsMessage.setText(ads.getDescription());
            jTextFieldAdress.setText(ads.getMapAddress());
            jTextFieldPhoneNumber.setText(ads.getPhoneNumber());
            jTextFieldYoutubeUrl.setText(ads.getYoutubeVideoUrl());
            jTextFieldwww.setText(ads.getWWW());
            jLabelImegaesPath.setText(ads.getFileUploadInput());
        }
    }
    private void setUsertoComponents(User user){
    	jTextFieldAccountName.setText(user.getLogin());
        jTextFieldRedirectUrl.setText(user.getRedirectUrl());
        persistUser(user);
        
    }
    private List<Ads> loadAds() {
        List<Ads> adsList;
        AdsIntf adsBc = AdsImpl.getInstance();
        adsList=new ArrayList<Ads>();
        adsList = adsBc.getAdsList();
        if (adsList != null && !adsList.isEmpty()) {
            return adsList;
        }
        return null;
    }
   

    private void setAdsNameList() {
       List<Ads> adslist=new ArrayList<Ads>();
       adslist.addAll(loadAds());
       jComboBoxAds.removeAllItems();
        if (adslist!=null && !adslist.isEmpty()) {
            for (Ads one :adslist){
                jComboBoxAds.addItem(new ComboItem(one.getTitle(),""+one.getId()));
            }
        } else {
            jComboBoxAds.addItem(new String("No items"));
        }
    }

    private Ads persistAds(String valueAdsId) {
        AdsIntf adsBc =  AdsImpl.getInstance();
        Ads ads = null;
        ads = adsBc.getAdsById(Integer.parseInt(valueAdsId));
        if (ads != null) {
            this._ads = ads;
        }
        return _ads;
    }
    private User persistUser(User user){
        this._user=user;
     return  _user;
    }

    private void setAllFildsToAds(){
        _ads.setTitle(jTextFieldAdsTitle.getText()!=null?jTextFieldAdsTitle.getText():"");
        _ads.setDescription(jTextAreaAdsMessage.getText()!=null?jTextAreaAdsMessage.getText():"");
        _ads.setMapAddress(jTextFieldAdress.getText()!=null?jTextFieldAdress.getText():"");
        _ads.setFileUploadInput(jLabelImegaesPath.getText()!=null?jLabelImegaesPath.getText():"");
        _ads.setYoutubeVideoUrl(jTextFieldYoutubeUrl.getText()!=null?jTextFieldYoutubeUrl.getText():"");
        _ads.setPhoneNumber(jTextFieldPhoneNumber.getText()!=null?jTextFieldPhoneNumber.getText():"");        
        if(jTextFieldwww.getText()!=null && jTextFieldwww.getText().length()>0 && !jTextFieldwww.getText().toLowerCase().contains("www.")){
        	_ads.setWWW("www."+jTextFieldwww.getText());
        }else {
        	_ads.setWWW(jTextFieldwww.getText());
        }
    }
    private void setAllFildsToUser() {
        if (checkPassword()) {
            _user.setLogin(jTextFieldAccountName.getText());
            _user.setRedirectUrl(jTextFieldRedirectUrl.getText());
            _user.setPassword(new String(jPasswordFieldNewPassword.getPassword()));
        }
    }
    private boolean checkPassword() {
    	char[] oldPassword =_user.getPassword().toCharArray();
        char[] verifyToBeChangedPassword = jPasswordFieldOldPassword.getPassword();
        char[] newPassword = jPasswordFieldNewPassword.getPassword();
        char[] confirmPassword = jPasswordFieldConfirmationNewPassword.getPassword();
        if (Arrays.equals(oldPassword,verifyToBeChangedPassword)) {
            if (Arrays.equals(newPassword,confirmPassword)) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this,
                        "Parola noua nu coincide.",
                        "Inane warning",
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Parola veche nu este corecta.",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        }
        return false;
    }
    private void deleteAds(){
        if (_ads!=null && _ads.getId()>0) {
           AdsIntf adsBc =  AdsImpl.getInstance();
           adsBc.deleteAds(_ads);
        }
        setAdsNameList();
    }
    private void newAds() {
        jTextFieldAdsTitle.setText("");
        jTextAreaAdsMessage.setText("");
        jTextFieldAdress.setText("");
        jTextFieldPhoneNumber.setText("");
        jTextFieldYoutubeUrl.setText("");
        jTextFieldwww.setText("");
        jLabelImegaesPath.setText("");
        _ads.setId(0);
    }

    private String getImagesName(File[] selectedFiles) {
        StringBuffer filesName=null;
         StringBuffer filesPath=null;
        if (selectedFiles.length > 0) {
            filesName = new StringBuffer();
            filesPath = new StringBuffer();
            File[] fileList = selectedFiles;
            filesName.append(fileList[0].getName());
            filesPath.append(fileList[0].getAbsolutePath());
            for (int i = 1; i < fileList.length; i++) {
                filesName.append(", " + fileList[i].getName());
                filesPath.append(", "+fileList[i].getAbsolutePath());
            }
            _ads.setImagePath(filesPath.toString());
        }
        return filesName.toString();
    }
    BuildInformation mainin;
    Thread thread;
    private void postAds(){
    	mainin=new BuildInformation(this.jTextFieldIntervalTime.getText());
      thread=new Thread(mainin);
    }
   
}
